name: seri_flutter_app
description: SERI_Flutter_App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.3
  shared_preferences: 2.0.5
  provider: 5.0.0
  splashscreen: 1.3.5
  sizer: 2.0.13
  intent: 1.4.0
  url_launcher: 6.0.3
  google_fonts: 2.1.0
  configurable_expansion_tile: 1.0.0
  group_radio_button: 1.1.0
  dio: 4.0.0
  flushbar: 1.10.4
  intl: 0.17.0
  pinput: 1.2.0
  flutter_svg: 0.22.0
  get: 4.1.4
  rflutter_alert: 2.0.2
  sms_otp_auto_verify: 1.2.2
  badges: 2.0.1
  carousel_slider: 3.0.0
  cached_network_image: 3.0.0
  connectivity: 3.0.6
  pinch_zoom: 0.1.0
  carousel_pro: 1.0.0
  flutter_text_to_speech: 3.0.7
  speech_to_text: 2.3.0
  lottie: ^1.0.1
  share_plus: ^2.1.2
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#47366F"
  image: assets/branding/splash_logo.png
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/logo.png"


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/stationary/
    - assets/Logo/
    - assets/
    - assets/animations/sharingRocket.json
    - assets/animations/

